<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.kouleen.minecraft</groupId>
        <artifactId>minecraft-parent</artifactId>
        <version>1.0.8</version>
    </parent>

    <groupId>io.github.kouleen.minecraft.plugin</groupId>
    <artifactId>minecraft-plugin</artifactId>
    <name>minecraftplugin</name>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <spigot-api.version>1.12.2-R0.1-SNAPSHOT</spigot-api.version>
        <bungeecord-api.version>1.12-SNAPSHOT</bungeecord-api.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.kouleen.minecraft.core</groupId>
            <artifactId>minecraft-core</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.milkbowl.vault</groupId>
                <artifactId>Vault</artifactId>
                <version>1.7.1</version>
            </dependency>
            <dependency>
                <groupId>javax.mail</groupId>
                <artifactId>mail</artifactId>
                <version>1.4.7</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>